"use client"

import { useState } from "react"
import { SparrowLogo } from "./sparrow-logo"
import { Button } from "./ui/button"

interface TermsAndConditionsProps {
  onAccept: () => void
}

export function TermsAndConditions({ onAccept }: TermsAndConditionsProps) {
  const [accepted, setAccepted] = useState(false)

  return (
    <div className="min-h-screen bg-black text-white flex items-center justify-center p-4">
      <div className="max-w-2xl w-full space-y-8">
        <div className="text-center space-y-4">
          <SparrowLogo className="w-16 h-16 mx-auto" />
          <h1 className="text-3xl font-bold">Terms and Conditions</h1>
          <p className="text-gray-400">Please read and accept our terms to continue</p>
        </div>

        <div className="bg-gray-900 rounded-lg p-6 max-h-96 overflow-y-auto space-y-4">
          <div className="space-y-4 text-sm text-gray-300 leading-relaxed">
            <h3 className="text-white font-semibold text-base">1. Disclaimer of Liability</h3>
            <p>
              Sparrow AI is provided "as is" without any warranties. We are not liable for any damages, losses, or
              issues that may arise from using this application, including but not limited to data loss, security
              breaches, or any consequences of generated code.
            </p>

            <h3 className="text-white font-semibold text-base">2. API Key Privacy</h3>
            <p>
              Your OpenRouter API key is stored locally in your browser's storage only. We do not collect, transmit, or
              store your API keys on our servers. You are responsible for keeping your API key secure and managing its
              usage.
            </p>

            <h3 className="text-white font-semibold text-base">3. Generated Content</h3>
            <p>
              All code and content generated by Sparrow AI comes from third-party AI models via OpenRouter. We are not
              responsible for the accuracy, security, or functionality of generated code. Always review and test
              generated code before use in production.
            </p>

            <h3 className="text-white font-semibold text-base">4. Usage Responsibility</h3>
            <p>
              You are solely responsible for your use of Sparrow AI and any consequences thereof. This includes API
              usage costs, compliance with OpenRouter's terms of service, and ensuring generated content meets your
              requirements.
            </p>

            <h3 className="text-white font-semibold text-base">5. No Data Collection</h3>
            <p>
              Sparrow AI does not collect personal data, chat history, or generated code. All data remains in your local
              browser storage. We do not have access to your conversations or projects.
            </p>
          </div>
        </div>

        <div className="space-y-4">
          <label className="flex items-start space-x-3 cursor-pointer">
            <input
              type="checkbox"
              checked={accepted}
              onChange={(e) => setAccepted(e.target.checked)}
              className="mt-1 w-4 h-4 bg-gray-800 border-gray-600 rounded focus:ring-blue-500"
            />
            <span className="text-sm text-gray-300">
              I have read and accept the terms and conditions. I understand that Sparrow AI is not liable for any issues
              and that my API key is stored locally only.
            </span>
          </label>

          <Button
            onClick={onAccept}
            disabled={!accepted}
            className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-gray-700 disabled:cursor-not-allowed"
          >
            Accept and Continue
          </Button>
        </div>
      </div>
    </div>
  )
}
